export const types = {
    //login
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    CLEAR_LOGIN_STATE: "CLEAR_LOGIN_STATE",

    //get categories
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

    //create category
    CREATE_CATEGORY: "CREATE_CATEGORY",
    CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

    //clear category state
    CLEAR_CATEGORY_STATE:"CLEAR_CATEGORY_STATE",

    // Products
    PRODUCT_LIST: "PRODUCT_LIST",
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAILURE: "PRODUCT_LIST_FAILURE",
    PRODUCT_DETAILS: "PRODUCT_DETAILS",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAILURE: "PRODUCT_DETAILS_FAILURE",
    PRODUCT_SEARCH: "PRODUCT_SEARCH",
    PRODUCT_SEARCH_SUCCESS: "PRODUCT_SEARCH_SUCCESS",
    PRODUCT_SEARCH_FAILURE: "PRODUCT_SEARCH_FAILURE",
}   