export const types = {
    //login
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    CLEAR_LOGIN_STATE: "CLEAR_LOGIN_STATE",

    //get categories
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

    //create category
    CREATE_CATEGORY: "CREATE_CATEGORY",
    CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

    //clear category state
    CLEAR_CATEGORY_STATE:"CLEAR_CATEGORY_STATE",

    // Products
    PRODUCT_LIST: "PRODUCT_LIST",
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAILURE: "PRODUCT_LIST_FAILURE",
    PRODUCT_DETAILS: "PRODUCT_DETAILS",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAILURE: "PRODUCT_DETAILS_FAILURE",
    PRODUCT_SEARCH: "PRODUCT_SEARCH",
    PRODUCT_SEARCH_SUCCESS: "PRODUCT_SEARCH_SUCCESS",
    PRODUCT_SEARCH_FAILURE: "PRODUCT_SEARCH_FAILURE",

    //address
    ADDRESS_LIST: "ADDRESS_LIST",
    ADDRESS_LIST_SUCCESS: "ADDRESS_LIST_SUCCESS",
    ADDRESS_LIST_FAILURE: "ADDRESS_LIST_FAILURE",

    CREATE_ADDRESS: 'CREATE_ADDRESS',
    CREATE_ADDRESS_SUCCESS: 'CREATE_ADDRESS_SUCCESS',
    CREATE_ADDRESS_FAILURE: 'CREATE_ADDRESS_FAILURE',
    
    DELETE_ADDRESS: "DELETE_ADDRESS",
    DELETE_ADDRESS_SUCCESS: 'DELETE_ADDRESS_SUCCESS',
    DELETE_ADDRESS_FAILURE: 'DELETE_ADDRESS_FAILURE',


    // Cart 
    GET_CART: "GET_CART",
    GET_CART_SUCCESS: "GET_CART_SUCCESS",
    GET_CART_FAILURE: "GET_CART_FAILURE",

    // Cart Item
    GET_CART_ITEM: "GET_CART_ITEM",
    GET_CART_ITEM_SUCCESS: "GET_CART_ITEM_SUCCESS",
    GET_CART_ITEM_FAILURE: "GET_CART_ITEM_FAILURE",


    CREATE_CART: "CREATE_CART",
    CREATE_CART_SUCCESS: "CREATE_CART_SUCCESS",
    CREATE_CART_FAILURE: "CREATE_CART_FAILURE",

    UPDATE_CART: "UPDATE_CART",
    UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
    UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",
    
    UPDATE_CART_QTY: "UPDATE_CART_QTY",
    UPDATE_CART_QTY_SUCCESS: "UPDATE_CART_QTY_SUCCESS",
    UPDATE_CART_QTY_FAILURE: "UPDATE_CART_QTY_FAILURE",

    CART_LIST: "CART_LIST",
    CART_LIST_SUCCESS: "CART_LIST_SUCCESS",
    CART_LIST_FAILURE: "CART_LIST_FAILURE",

    // Add CartItem
    ADD_CART_ITEM: "ADD_CART_ITEM",
    ADD_CART_ITEM_SUCCESS: "ADD_CART_ITEM_SUCCESS",
    ADD_CART_ITEM_FAILURE: "ADD_CART_ITEM_FAILURE",

    // Update CartItem
    UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
    UPDATE_CART_ITEM_SUCCESS: "UPDATE_CART_ITEM_SUCCESS",
    UPDATE_CART_ITEM_FAILURE: "UPDATE_CART_ITEM_FAILURE",

    //customer 
    GET_CUST_GENDER: 'GET_CUST_GENDER',
    GET_CUST_GENDER_SUCCESS: 'GET_CUST_GENDER_SUCCESS',
    GET_CUST_GENDER_FAILURE: 'GET_CUST_GENDER_FAILURE',

    GET_CUST_ACTIVITY: 'GET_CUST_ACTIVITY',
    GET_CUST_ACTIVITY_SUCCESS: 'GET_CUST_ACTIVITY_SUCCESS',
    GET_CUST_ACTIVITY_FAILURE: 'GET_CUST_ACTIVITY_FAILURE',

    GET_CUST_DIET: 'GET_CUST_DIET',
    GET_CUST_DIET_SUCCESS: 'GET_CUST_DIET_SUCCESS',
    GET_CUST_DIET_FAILURE: 'GET_CUST_DIET_FAILURE',
    
    GET_CUST_GOAL: 'GET_CUST_GOAL',
    GET_CUST_GOAL_SUCCESS: 'GET_CUST_GOAL_SUCCESS',
    GET_CUST_GOAL_FAILURE: 'GET_CUST_GOAL_FAILURE',

    POST_CUST_DATA: 'POST_CUST_DATA',
    POST_CUST_DATA_SUCCESS: 'POST_CUST_DATA_SUCCESS',
    POST_CUST_DATA_FAILURE: 'POST_CUST_DATA_FAILURE',

    SAVE_USER_DATA: 'SAVE_USER_DATA',

    //meal plan
    MEAL_PLAN_ID: 'MEAL_PLAN_ID',

    // mealplans
    MEALPLANS_LIST: "MEALPLANS_LIST",
    MEALPLANS_LIST_SUCCESS: "MEALPLANS_LIST_SUCCESS",
    MEALPLANS_LIST_FAILURE: "MEALPLANS_LIST_FAILURE",


    MEALPLAN_DETAILS: "MEALPLAN_DETAILS",
    MEALPLAN_DETAILS_SUCCESS: "MEALPLAN_DETAILS_SUCCESS",
    MEALPLAN_DETAILS_FAILURE: "MEALPLAN_DETAILS_FAILURE",

     //postal codes 
    GET_POSTALCODES: 'GET_POSTALCODES',
    GET_POSTALCODES_SUCCESS: 'GET_POSTALCODES_SUCCESS',
    GET_POSTALCODES_FAILURE: 'GET_POSTALCODES_FAILURE',

    //signup
    AUTH_LOADING: 'AUTH_LOADING',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    AUTH_ERROR: 'AUTH_ERROR',

    GET_SESSION_TOKEN_SUCCESS:"GET_SESSION_TOKEN_SUCCESS",
    GET_SESSION_TOKEN_FAILURE:"GET_SESSION_TOKEN_FAILURE",
    DELETE_CART_ITEM: "DELETE_CART_ITEM",
    DELETE_CART_ITEM_SUCCESS: "DELETE_CART_ITEM_SUCCESS",
    DELETE_CART_ITEM_FAILURE: "DELETE_CART_ITEM_FAILURE",

}   