import React from "react";
import { Card, Button } from "react-bootstrap";
import "./style.css";
import AlmondBannanabar from "../../assets/home/almond-banana-bar.png";
import LandingCarousel from "../carousel";
import { useSelector } from "react-redux";
import OwlCarousel from "react-owl-carousel";
import chocoimg from "../../assets/home/StoreChoc.png";
import test from "../../assets/default_thumbnail.png";
import { useHistory } from "react-router-dom";
import FooterContent from "../../scenes/Footer/index";

const PrivacyPolicyContent = () => {
  const products = useSelector((state) => state.products);
  const categories = useSelector((state) => state.categories);
  console.log("categories", categories.categories);
  const history = useHistory();
  return (
      <>
        <div className="oe_structure oe_empty">
        <section className="pt32 pb0" data-name="Title">
            <div className="container">
                <div className="row s_nb_column_fixed">
                    <div className="col-lg-12 s_title pt16 pb16">
                        <h1 className="s_title_default">
                            <font>Legal</font>
                        </h1>
                    </div>
                </div>
            </div>
        </section>
        <section className="s_text_block pb32 pt0" data-name="Text block">
            <div className="container">
                <div className="row">
                    <div className="pb32 offset-lg-1 col-lg-10 pt0">
                        <p className="tc_lead">These policies are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, and are an ‘electronic record’ as contemplated under section 2(t) of the Information Technology Act, 2000 and the Rules thereunder. These Terms being an electronic record are generated by a computer system and do not require any physical or digital signatures.</p>
                        <p className="tc_lead">
                            <br/>
                        </p>
                        <p className="tc_lead">
                            <font className="text-beta fs-24">
                                <b>ACCESS TO THE WEBSITE</b>
                            </font>
                        </p>
                        <p className="tc_lead">The Website is owned by Vibrant Living Private Limited having registered office at #107, Prashanth Hills, Raidurg, Nav Khalsa, Hyderabad TS 500104 (Vibrant Living). Use of the Website by the user (“You”/ “User”) is subject to the terms and conditions contained herein.</p>
                        <p className="tc_lead">Accessing, browsing or otherwise using the Website will be construed as Your unequivocal and irrevocable acceptance and acknowledgement to the terms and conditions contained under Terms of Use and binding policies hereof. By using the Website, You declare to have carefully read, understood and agree to be bound by these Terms of Use. Vibrant Living may at its sole discretion allow or disallow access to Website and reserves the right to change any of the terms and conditions contained herein at any point in time. It is Your responsibility to periodically review these Terms of Use any update and changes and Your continued use of the Website will be considered as Your acceptance to such updates and changes.</p>
                        <p className="tc_lead">
                            <br/>
                        </p>
                        <p className="tc_lead">
                            <font className="text-beta fs-24">
                                <b>ELIGIBILITY</b>
                            </font>
                        </p>
                        <p className="tc_lead">You should have completed 18 years of age and be competent to enter into a contract under Indian contract law. If You are under 18 years of age who is intending to avail the services of the Website should do so through Your legal guardian in accordance with applicable law.&nbsp;</p>
                        <p className="tc_lead">If You are using the Website on behalf of any corporation, company, institution, association or other entity, the person should be authorized by such corporation, company, institution, association or other entity to use and access the Website.</p>
                        <p className="tc_lead">Vibrant Living reserves the right to refuse access to use the services offered at the Website to new users or to terminate access granted to existing users at any time without any reasons for doing so.</p>
                        <p className="tc_lead">
                            <br/>
                        </p>
                        <p className="tc_lead">
                            <font className="text-beta fs-24">
                                <b>COMPLIANCE REQUIREMENTS</b>
                            </font>
                        </p>
                        <p className="tc_lead">Every User of the Website shall comply with all the applicable laws, including but not limited to the Foreign Exchange Management Act, 1999, notifications issued there under the Exchange Control Manual issued by the Reserve Bank of India, Customs Act, 1962, Information Technology Act, 2000, Prevention of Money Laundering Act, 2002, Foreign Contribution Regulation Act, 1976, Income Tax Act, 1961, Export Import Policy of the Government of India and shall include any amendments, notifications and Rules thereof under the aforesaid enactments applicable for using the Website or buying/ selling any product or service through the Website.</p>
                        <p className="tc_lead">
                            <br/>
                        </p>
                        <p className="tc_lead">
                            <font className="text-beta fs-24">
                                <b>USER ACCOUNT</b>
                            </font>
                        </p>
                        <p className="tc_lead">You may be required to register and set up an account (“Account”) for using the Website by entering an email address and password or by using any permitted social media the Website account to sign in ("Account Information"). Vibrant Living at its sole discretion may ask for the verification of Your Account Information provided by You and hence, it is advisable to provide a valid information e.g. like email address or mobile number etc. while creating an Account. The Website will set-up an account and email the details of the Account at the email address provided. You can also create and update an Account through Customer Support.</p>
                        <p className="tc_lead">You can create one Account only and it is not permitted to transfer or interchange such Account to any other person. The list of information required to be provided by You, the manner of usage, protection and confidentiality of Your information and Account information are more specifically dealt under the Website’s Privacy Policy and You are requested to read the Privacy Policy in detail before sharing Your information or creating an Account.</p>
                        <p className="tc_lead">
                            <br/>
                        </p>
                        <p className="tc_lead">
                            <font className="text-beta fs-24">
                                <b>PAYMENT POLICY</b>
                            </font>
                        </p>
                        <p className="tc_lead">Payment is an integral part of an online shopping experience. All payments shall be collected through secured payment options.</p>
                        <p className="tc_lead">We accept all prepaid payment options such as all the major Credit Cards, Debit Cards, Net-Banking etc. Vibrant Living may also offer Cash on Delivery for certain products and services.</p>
                        <p className="tc_lead">All payments for purchases made by You on the Website shall only be in Indian Rupees. In case of a prepaid transaction, after payment for the order has been successfully received by Vibrant Living, You will be sent a notification by email or SMS at the email address or mobile number provided to Vibrant Living confirming receipt of payment. There may be limits to the amount of Cash on Delivery payments based on pin codes or the State in India where delivery is to be made. Vibrant Living reserves the right to withdraw or block or limit Your purchases using Cash on Delivery on basis of your transaction history.</p>
                        <p className="tc_lead">
                            <b>Credit and Debit Card</b>
                        </p>
                        <p className="tc_lead">Vibrant Living accepts popular Visa, Master Card, Maestro, American Express and Diners cards. You will be redirected to Your issuing bank's site, where You will have to follow the instruction to complete the payment.</p>
                        <p className="tc_lead">
                            <b>Net Banking</b>
                        </p>
                        <p className="tc_lead">You can make payment for an order by using Your Net Banking account. The Website accepts payments for Your orders to sellers through various banks. You will be redirected to Your bank's site where You will be able to make payment after entering in Your login id and password that is known only to You.</p>
                        <p className="tc_lead">
                            <b>Cash on Delivery</b>
                        </p>
                        <p className="tc_lead">Cash on Delivery is one of the payment methods for making purchases on Vibrant Living where You don't have to make any advance payment.</p>
                        <p className="tc_lead">Cash on Delivery is available as a payment method for select products on Vibrant Living. Eligible products will be indicated by the message [‘Eligible for Cash on Delivery’] on the [‘product order page’] for delivery in certain pin codes.</p>
                        <p className="tc_lead">
                            <b>Issues with Payments - Pending Payments:</b>
                        </p>
                        <p className="tc_lead">Payments can sometimes fail or remain in the pending stage. Some of the reasons could be:</p>
                        <ol>
                            <li>
                                <p className="tc_lead">Incorrect debit or credit card details are entered.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Card may be blocked, or card details are no longer valid or need to be updated.</p>
                            </li>
                            <li>
                                <p className="tc_lead">The page is accidentally closed or refreshed, or backspace is pressed while the transaction is being processed by Your bank.</p>
                            </li>
                            <li>
                                <p className="tc_lead">The connection between Vibrant Living and Your bank or issuer failed due to some technical reasons and the transaction could not be completed.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Card or bank or issuer is not recognised by Vibrant Living.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Incorrect login or password details are entered.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Payment amount exceeds the limit mutually agreed to between You and Your bank or issuer.</p>
                            </li>
                        </ol>
                        <p className="tc_lead">If You face any of the above payment issues, try placing the order again in a short while or contact Your bank or issuer for technical assistance. Vibrant Living is not liable for any loss or inconvenience caused to You when making payment or for any wrongful debits to Your cards or net banking accounts.</p>
                        <p className="tc_lead">
                            <b>Issuing Bank Terms and Conditions</b>
                        </p>
                        <p className="tc_lead">Users understand and acknowledge that all payments made by the Users using valid credit card/ Debit card/ Cash Card/ and other payment instruments or mechanism including net banking facility will be processed using a payment gateway or appropriate payment system infrastructure and the same is governed by a separate set of terms and conditions agreed between the User and the respective Issuing Bank and payment instrument issuing company.</p>
                        <p className="tc_lead">
                            <b>Requirements of Permanent Account Number (PAN)</b>
                        </p>
                        <p className="tc_lead">For all the purchase of an amount equal to or exceeding INR 2,00,000 (INR two lakhs only), You will be required to upload a copy of Your PAN card, within such time as may be prescribed from the date of purchase, failing which, the purchase made by You will be automatically cancelled. The order shall also stand cancelled if there is a discrepancy between Your name in Account with Vibrant Living the name printed on the PAN card.</p>
                        <p className="tc_lead">The requirement to provide a copy of PAN card is one time activity and You don’t need to submit it again.</p>
                        <p className="tc_lead">
                            <br/>
                        </p>
                        <p className="tc_lead">
                            <font className="text-beta fs-24">
                                <b>DELIVERY POLICY</b>
                            </font>
                        </p>
                        <p className="tc_lead">
                            <b>Shipping Address</b>
                        </p>
                        <p className="tc_lead">Your shipping address and pin code will be verified with the database of Vibrant Living before You proceed to pay for Your purchase. In the event Your order is not serviceable by our logistics service providers or the area is not covered, we will request You to provide us with an alternate shipping address. You can make purchases on the Website from anywhere in the world but at the same time You must ensure the payment is processed and shipping addresses are valid postal addresses..</p>
                        <p className="tc_lead">When You submit an alternative address for delivery, You are responsible for accepting and collecting the package from such alternative address. Confirmation from the logistics service provider of successful delivery to the alternative shipping address is deemed as acceptance of delivery by You and Vibrant Living will have no liability in this regard. We deliver through 3rd party delivery system for the international shipments. Any consequences received at custom clearance should be taken care by you.</p>
                        <p className="tc_lead">Delivery to Partner Store (subject to the availability of function and the facilities by seller)</p>
                        <p className="tc_lead">Instead of delivering the order to Your shipping address, You can choose to have Your product delivered to a partner store so You can pick-up the package from the partner store at Your convenience. Upon collecting the package You will receive a notification by email or SMS at the email address or mobile number provided to Vibrant Living confirming delivery of the product. If You do not collect the product from the partner store within allowed time, the product will be returned to the seller and Your order will be cancelled. No refund due to non-deliverability will be applicable to orders placed with Cash on Delivery options.</p>
                        <p className="tc_lead">
                            <b>Delivery by Vibrant Living or Seller</b>
                        </p>
                        <p className="tc_lead">The delivery of the ordered products from the seller to You will be made by logistics service providers assigned by Vibrant Living or Sellers. However, large and bulky products may be delivered to You directly by the seller. Deliveries cannot be rescheduled after the order has been placed.</p>
                        <p className="tc_lead">The logistics service provider assigned by Vibrant Living will make a maximum of two [2] attempts to deliver Your order. In case You are not reachable, available or do not accept delivery of products in these attempts Vibrant Living reserves the right to cancel the order at its discretion. You may be informed of such cancellation by email or SMS at the email address or mobile number provided to Vibrant Living. The cancelled order is returned to the seller. You agree not to hold Vibrant Living liable for any cancellation.</p>
                        <p className="tc_lead">If You wish to request the Website to resend the product, You can do so by placing a new order for the product on the terms set out on the [‘product order page’] when You place the new order. Your order will be accepted subject to availability of the product.</p>
                        <p className="tc_lead">In case there is any dispute regarding the shipment of the product or serviceability for the area not covered by the logistics service providers, Vibrant Living will not be responsible for the non-delivery of the product.</p>
                        <p className="tc_lead">Title and risk of loss for all products ordered by You shall pass on to You upon delivery of the products at the shipping address provided by You.</p>
                        <p className="tc_lead">
                            <b>Multiple Product Orders</b>
                        </p>
                        <p className="tc_lead">In case You order multiple products in one transaction, Vibrant Living would endeavour to ship all products together. However, this may not always be possible due to some product characteristics or logistics issues or the location of the seller and You may receive the products separately and at different times. If You purchase multiple products in a single transaction, then all the products would be dispatched to a single shipping address given by You. If You wish to ship products to different addresses, then You should book the orders separately based on the shipping addresses.</p>
                        <p className="tc_lead">
                            <b>Missing Items</b>
                        </p>
                        <p className="tc_lead">In the event, the product package received by You is missing one or more products or accessories or does not include the freebie or the order is partly delivered, You should inform Vibrant Living through the Customer Care Team within 5 days of delivery date of the package. Missing products claims will not be accepted after 3 days from delivery date.</p>
                        <p className="tc_lead">When a package delivered is missing one or more products or accessories, You are requested to return the original package delivered to the seller in accordance with the Return Policy.</p>
                        <p className="tc_lead">
                            <b>Refusal of Delivery</b>
                        </p>
                        <p className="tc_lead">Before accepting delivery of any product, kindly ensure that the product's packaging is not damaged or tampered. If You observe that the package is damaged or tampered, You are requested to refuse to accept delivery and inform Vibrant Living within 3 days of delivery date.</p>
                        <p className="tc_lead">You are requested to fill the delivery sheet / acknowledgement used by the logistics service providers and note down the condition of the delivered package. Damaged or tampered products claims will not be accepted beyond the returns policy.</p>
                        <p className="tc_lead">In the event of dispute, Vibrant Living will coordinate with You and the seller to reach an amicable solution. Vibrant Living is only a facilitating link between You and the seller and will not be liable in any manner.</p>
                        <p className="tc_lead">
                            <b>Delivery Time</b>
                        </p>
                        <p className="tc_lead">An estimated delivery time of each product will be displayed on the [‘product order page’]. On placing Your order, You will receive an email or SMS at the email address or mobile number provided to Vibrant Living containing a summary of the order and also the estimated delivery time to Your location. The seller may take additional time to pack and dispatch certain products and this time will be indicated by the message on the [‘product order page’]. This period of time is to be added to the shipping speed You choose.</p>
                        <p className="tc_lead">Delivery timeframes are just estimates and are not guaranteed delivery timeframes and should not be relied upon as such. Deliveries to certain locations may take longer than expected due to accessibility of the location and serviceability by the logistics service provider.</p>
                        <p className="tc_lead">
                            <b>About Delayed Delivery</b>
                        </p>
                        <p className="tc_lead">Sometimes, delivery may take longer due to:</p>
                        <ol>
                            <li>
                                <p className="tc_lead">Bad weather.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Transportation delays.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Natural calamities.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Political disruptions.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Logistics service provider related challenges.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Product lost in transit.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Regional or national holidays which are considered as delivery holidays.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Other unforeseen circumstances or events beyond the control of Vibrant Living or logistics service provider.</p>
                            </li>
                        </ol>
                        <p className="tc_lead">If the estimated delivery date has passed and You still have not received Your order, please contact us and we will take steps to track Your package. In such cases, we may also try to proactively contact You. Please check Your emails and SMS regularly for such updates.</p>
                        <p className="tc_lead">Vibrant Living will not compensate for any mental agony or inconvenience or loss caused due to delay in delivery for any reason. You may be informed by email or SMS at the email address or mobile number provided to Vibrant Living if any product in the order is unavailable or is delayed or lost in transit.</p>
                        <p className="tc_lead">
                            <b>Shipping Charges</b>
                        </p>
                        <p className="tc_lead">You may be required to pay Shipping Charges in addition to the order value amount. The shipping charges, if any, will appear at the time of checkout. All delivery charges are inclusive of service tax unless stated otherwise. Shipping Charges may vary for different pin codes because of the increase in shipping cost or seller’s is located in a different area. Delivery charges will vary according to pin codes as well as type of product.</p>
                        <p className="tc_lead">
                            <b>Open delivery</b>
                        </p>
                        <p className="tc_lead">Vibrant Living reserves the right to provide Open delivery or not. Open delivery service which is provided by Vibrant Living with some Specifics logistics service providers. Open delivery depends upon our logistics service provider’s service dependencies. You can’t open parcel if logistics service provider doesn’t allow and in such event, You have a right to accept the parcel after paying the amount and thereafter You can use our hassle-free return policy.</p>
                        <p className="tc_lead">Please refer to the Return and Refund Policies, if You wish to return the delivered product to Vibrant Living.</p>
                        <p className="tc_lead">&nbsp;</p>
                        <p className="tc_lead">
                            <font className="text-beta fs-24">
                                <b>RETURN POLICY</b>
                            </font>
                        </p>
                        <p className="tc_lead">
                            <b>Reasons for Return</b>
                        </p>
                        <p className="tc_lead">Return Policy makes it possible for You to return a product if You receive a damaged or defective product or if the product is significantly different from what was purchased or when the package delivered is missing one or more products or accessories. Return Policy here should be read in conjunction with any specific terms and conditions applicable to a product which can be found on the product descriptions page for returning a product.</p>
                        <p className="tc_lead">
                            <b>Conditions for Return</b>
                        </p>
                        <p className="tc_lead">In order to return any product sold through the Website, You are required to comply with the below mentioned conditions, viz.:</p>
                        <ol>
                            <li>
                                <p className="tc_lead">The return has to be in compliance with the Return Policy associated with the product category.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Vibrant Living should be notified of the receipt of a damaged or defective product or if the product is significantly different from what was purchased, within the period mentioned in the returns policy.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Products should be returned unused, in their original packaging along with the original price tags, labels, packing, barcodes, user manual, warranty card and invoices, accessories, freebies and original boxes defined as essentials. If any product is returned without the essentials, the product shall not be accepted for return and shall be sent back to You.</p>
                            </li>
                            <li>
                                <p className="tc_lead">The return packages should be strongly and adequately packaged so that there is no damage of products during transit.</p>
                            </li>
                            <li>
                                <p className="tc_lead">The returned products are subject to verification and quality checks by the sellers selling on Vibrant Living in order to determine the legitimacy of the complaint or return.</p>
                            </li>
                            <li>
                                <p className="tc_lead">If You have chosen the partner store option for delivery of the order and wish to return the product, You should return the product to the same store from where You collected the order or to other store that the partner might allow from time to time. You should return the product in original and unused condition along with all original price tags, labels, packing, barcodes, user manuals, warranty card and invoices, accessories, freebies and boxes received. Store reserves the right to accept the product and after quality check.</p>
                            </li>
                            <li>
                                <p className="tc_lead">You should fill the Return Form provided by Vibrant Living with the originally delivered package or made available to You over email or account and include it in the returned package. Return requests are not processed if the Return Form is incomplete or absent in the returned package received. The reason for return should be stated in the Return form. You should additionally fill out the delivery sheet used by the logistics service providers and note down any damaged or tampered condition of the delivered package.</p>
                            </li>
                            <li>
                                <p className="tc_lead">The return has to be in compliance with the return policy of the seller or the manufacturer of the product where applicable.</p>
                            </li>
                        </ol>
                        <p className="tc_lead">
                            <b>Non-returnable Products&nbsp;</b>
                        </p>
                        <p className="tc_lead">All products cannot be returned. Some of the products that cannot be returned are:</p>
                        <ol>
                            <li>
                                <p className="tc_lead">Innerwear, lingerie, socks, clothing freebies and swimsuits.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Perfumes, personal and beauty care or other consumables.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Products that have been used or installed.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Products damaged due to misuse of product or products having incidental damages due to malfunctioning.</p>
                            </li>
                            <li>
                                <p className="tc_lead">A product with defects not covered under manufacturer’s warranty.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Products with tampered or missing serial numbers.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Personalised or engraved products or resized products.&nbsp; &nbsp;</p>
                            </li>
                            <li>
                                <p className="tc_lead">Products sold in sets or combinations cannot be returned individually.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Any other product depending upon the Return Policy in force.</p>
                            </li>
                        </ol>
                        <p className="tc_lead">If You are unable to inform Vibrant Living of the receipt of a damaged or defective product or the product is not as per specifications of Your order or the package delivered is missing one or more products or accessories as per the returns policy and procedure, Vibrant Living or Seller shall not be obliged to accept the returned product or be liable in this regard. In the event, such product is sent to Seller, the product will be returned to the Customer and the same needs to be accepted from Seller or assigned logistics service provider. Vibrant Living or seller will not be responsible if the product is not accepted and no refund will be issued.</p>
                        <p className="tc_lead">
                            <b>Damaged, Defective or Other Non-conforming Products</b>
                        </p>
                        <p className="tc_lead">Returns of damaged, defective or other products eligible for return are accepted as under:</p>
                        <ol>
                            <li>
                                <p className="tc_lead">In the event You receive a damaged or defective product or a product that does not comply with the specifications as per Your original or the product is delivered after the expected delivery period or the package delivered is missing one or more products or accessories and eligible for return as described by Return Policy, You are required to get in touch with the Customer Care Team through any of the below mentioned channels or submit a return request online (if such facility is available) as per the Returns Policy.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Upon receiving Your return request, Vibrant Living shall verify the authenticity and the nature of the request and if the request is genuine, Vibrant Living will inform the seller of the return request and will ask the seller for a refund to be processed upon the receipt and quality check of the returned product. It will take a minimum of [ 4-6] business days to process Your request for return of products.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Vibrant Living or Seller may arrange for pick-up of the product through an assigned logistics service provider. You will receive an email or SMS notification at Your email address or mobile number provided to Vibrant Living. In the event Vibrant Living is unable to arrange pick-up, Vibrant Living will notify You regarding the same and You will be required to send the product to the seller at the provided address using a reputed courier service in Your area.</p>
                            </li>
                            <li>
                                <p className="tc_lead">For return of large and bulky products such as televisions, refrigerators, air-conditioners, etc. the seller will arrange for pickup.</p>
                            </li>
                            <li>
                                <p className="tc_lead">If Your pin code is not serviceable, Vibrant Living may ask You to ship the product to the seller using a relevant and available logistics service provider or Indian Postal services. Customers are required to submit the shipping information of the self-ship by contact Customer Service. In the event the details are not provided and the shipment arrives without returns form or invoice, the refund may be delayed.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Upon receipt of the returned product by the seller and successful completion of the quality check, You will receive an email or SMS confirmation at the email address or mobile number provided to Vibrant Living.</p>
                            </li>
                            <li>
                                <p className="tc_lead">
                                    <span>You will be refunded the product cost along with taxes and shipping charges, if any. Courier freight charges You paid to courier or shipping service for returning the product to seller will be reimbursed as per method agreed with You.</span>
                                    <span>&nbsp;</span>
                                    <br/>
                                </p>
                            </li>
                        </ol>
                        <p className="tc_lead">You expressly acknowledge that the seller is solely responsible for the damaged or defective product or a product that does not meet the specifications of Your original order or delayed delivery of the order or delivery of the package with one or more products or accessories missing and for any claims that You may have in relation to such products and Vibrant Living shall not in any manner be held liable for the same. In the event of dispute, Vibrant Living will coordinate with You and the seller to reach an amicable solution. For certain products Vibrant Living is only a facilitating link and an Intermediary as per definition under Information Technology Act, 2000 and rules framed thereunder, between You and the seller and Vibrant Living will not be liable in any manner.</p>
                        <p className="tc_lead">
                            <b>Period for Return</b>
                        </p>
                        <p className="tc_lead">Please refer “Know More” section of the product information page for the Period of Return i.e. period within which a product delivered can be returned by the Buyer subject to the other terms and conditions of the Return Policy contained hereunder.</p>
                        <p className="tc_lead">
                            <b>Cancellation of Return Request</b>
                        </p>
                        <p className="tc_lead">A request for return once made can be cancelled by contacting Customer Service. In case the Logistics Service provider arrives to receive the shipment and You want to cancel the request, You may choose to inform the logistics service provider that You do not wish to return the product. You will receive an email or SMS notification at the email address or mobile number provided to Vibrant Living cancelling Your return request.</p>
                        <p className="tc_lead">
                            <b>Refusal of Return Request</b>
                        </p>
                        <p className="tc_lead">Vibrant Living reserves the right to refuse or cancel any return request.&nbsp; If the request for returns is not allowed by the Returns Policy, You will not be refunded the payment made or any costs and will not be able to raise a second request for return for the same product. You agree not to dispute the decision made by Vibrant Living and accept Vibrant Living’s decision regarding the refusal or cancellation and further agree not hold Vibrant Living liable for any refusal or cancellation.</p>
                        <p className="tc_lead">
                            <b>Frivolous Complaints</b>
                        </p>
                        <p className="tc_lead">In the event of frivolous or baseless complaints or requests regarding the quality or content of the products, Vibrant Living reserves the right to take necessary legal actions against You and You will be solely liable for all costs incurred by Vibrant Living in this regard.</p>
                        <p className="tc_lead">
                            <b>Return Shipping Process</b>
                        </p>
                        <p className="tc_lead">
                            <u>Self-send Process</u>
                        </p>
                        <p className="tc_lead">In case of return of products initiated and subsequent courier of the product by You, if it is found that the returned product was not delivered to the seller or any other designated location specified or the package was empty, the onus shall be on You to prove through submission of proof of delivery from the concerned courier service provider to establish Your claim of return. Self-courier of returns should be initiated within the periods specified in the Vibrant Living’s Returns Policy. Vibrant Living is not liable to process the return request until satisfactory proof of delivery is provided to Vibrant Living.</p>
                        <p className="tc_lead">In case of damage claims, Vibrant Living may ask for pictures of the damaged product before it is approved or allowed for return.</p>
                        <p className="tc_lead">For return shipping managed by Vibrant Living, You will need to hand over the product to the assigned logistics service provider at the time of pick-up. In the event the logistics service provider makes attempts to pick-up the product and You are unavailable or not ready to handover the product, Vibrant Living or logistics service provider will not be held responsible for the delay in pick-up or processing of the quality check by the seller and hence the refund. A maximum of 2 attempts will be made by the logistics service provider to pick-up the product to be returned. Vibrant Living will not be liable for the products returned by mistake.</p>
                        <p className="tc_lead">In the event where a product not belonging to the seller selling on Vibrant Living is returned by mistake, Vibrant Living is not accountable for such misplacement and is not responsible for its delivery back to You or any costs incurred by You or any refund.</p>
                        <p className="tc_lead">
                            <u>Discrepancy Between Information Provided by You and Our Logistics Service Provider</u>
                        </p>
                        <p className="tc_lead">In case of any discrepancy in the status of pick-up of a product arranged by Vibrant Living, (where You claim the product has been returned, while our system suggests otherwise) refund will be initiated only if You successfully furnish the courier slip given by the Vibrant Living assigned logistics service provider at the time of the pick-up.</p>
                        <p className="tc_lead">In case where a seller or designated return location claims that the product received from You is different or the return of the product is not in compliance with the Returns Policy, the product will be dispatched back to Your shipping address and You are required to receive and accept the package. In the event of dispute, Vibrant Living will coordinate with You and the seller to reach an amicable solution. Vibrant Living is only a facilitating link between You and the seller and will not be liable in any manner.</p>
                        <p className="tc_lead">&nbsp;</p>
                        <p className="tc_lead">
                            <b>
                                <font className="text-beta fs-24">ORDER CANCELLATION POLICY</font>
                            </b>
                        </p>
                        <p className="tc_lead">Cancellation of an order can be done either by Vibrant Living or by You as under:</p>
                        <p className="tc_lead">
                            <b>Cancellation by Vibrant Living</b>
                        </p>
                        <p className="tc_lead">Vibrant Living has the discretion to cancel an order. Some of the reasons for cancellation are as under (not being exhaustive list of reasons):</p>
                        <ol>
                            <li>
                                <p className="tc_lead">Your failure to comply with any of these terms.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Product is unavailable with the seller.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Technical errors or issues.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Any reason identified by Vibrant Living's credit and fraud avoidance team.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Invalid address or wrong address is given in order details.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Malpractices used to place the order.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Bulk order is placed for the likely commercial resale.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Multiple orders are placed for the same product at the same address.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Order is undelivered after three (3) attempts.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Failure to collect the order from the partner store within stipulated time.</p>
                            </li>
                            <li>
                                <p className="tc_lead">Pricing or specifications on any product as is shown on the Website due to typographical error or incorrect information inadvertently provided by the seller or some technical glitch, resulting into incorrect pricing or specifications.</p>
                            </li>
                        </ol>
                        <p className="tc_lead">Notwithstanding anything contained hereunder, Vibrant Living reserves the right, at its sole discretion, to refuse or cancel any order for any reason whatsoever without any further liability. On such cancellation, You will be sent a notification email or SMS at the email address or mobile number provided to Vibrant Living.</p>
                        <p className="tc_lead">You agree to release and indemnify Vibrant Living, its officers and representatives from any cost, damage, liability or any of the actions in case of cancellation of Your Order by Vibrant Living or seller.</p>
                        <p className="tc_lead">
                            <b>Cancellation by You</b>
                        </p>
                        <p className="tc_lead">You may cancel an order for any reason, although cancellation by You must be done before the product has been shipped for delivery to You. No cancellation is permitted subsequently.</p>
                        <p className="tc_lead">You can cancel an order, or part of an order where multiple products have been ordered. This can be done either by calling or emailing Customer Care Team or in Your account on the Website through ‘my account’. You should state the reason for such cancellation. Vibrant Living will process the request for cancellation as per the policy in force.</p>
                        <p className="tc_lead">If an order has been successfully cancelled, You will be sent a confirmation email or SMS at the email address or mobile number provided to Vibrant Living.</p>
                        <p className="tc_lead">Vibrant Living reserves the right to accept or reject requests for order cancellations for any reason whatsoever. You agree not to hold Vibrant Living liable for any rejection of order cancellations.</p>
                        <p className="tc_lead">You will receive a refund for Your cancelled orders that have been accepted in accordance with the Refund Policy.</p>
                        <p className="tc_lead">&nbsp;</p>
                        <p className="tc_lead">
                            <b>
                                <font className="text-beta fs-24">REFUND POLICY</font>
                            </b>
                        </p>
                        <p className="tc_lead">
                            <b>Refunds</b>
                        </p>
                        <p className="tc_lead">Refunds are provided for cancellation / return of products, subject to the eligible cancellation/ return as per Return Policy or these terms and conditions, initiated in accordance with the Return or Cancellation Policy.</p>
                        <p className="tc_lead">Refund is made for the full amount of the order or part order successfully cancelled that was paid by You for the delivery of the order.</p>
                        <p className="tc_lead">For return requests, the refund of payment is made after the returned product has been received by the seller and has passed the quality checks. The entire product cost along with any taxes and shipping charges if any will be refunded to You.</p>
                        <p className="tc_lead">If any refund is received by You pending the quality checks, You will hold such amounts in trust on behalf of Vibrant Living until conclusion of such quality checks unless claimed by Vibrant Living any time before that. If You are in receipt of any wrongful refunded or payment, You will transfer such amount back to Vibrant Living within 3 days of You receiving such amount.</p>
                        <p className="tc_lead">No refund due to non-deliverability will be applicable to orders placed with Cash on Delivery options. Refund of Cash on Delivery orders returned by You may subject to levy of a charge which will be deducted from Your refund amount.</p>
                        <p className="tc_lead">
                            <b>Time Period for Refunds</b>
                        </p>
                        <p className="tc_lead">Refunds are normally processed within 1-6 working days after the completion of quality checks of product returned and further depends on various banking and payment channels.</p>
                        <p className="tc_lead">Interest charged by the bank providing the EMI Scheme till the time the request for return or cancellation is raised will not be refunded.&nbsp;</p>
                        <p className="tc_lead">Vibrant Living is not responsible for any errors or delays in refund due to banks or third-party service provider errors or delays.</p>
                        <p className="tc_lead">
                            <b>Mode of Refund</b>
                        </p>
                        <p className="tc_lead">The mode of refund of payments cannot be changed at any stage as the refund amount is transferred to Your source account. Refunds are paid back to the source of payment.</p>
                        <p className="tc_lead">Refund for payments made by modes other than Cash on Delivery, which fail when processed back to source may be refunded by National Electronic Funds Transfer (“NEFT”) to Your bank account.</p>
                        <p className="tc_lead">Refund of orders placed using Cash on Delivery as the payment method will be made by cheque or demand draft or to Your bank account via NEFT or to Your wallet account depending on the discretion of Vibrant Living.</p>
                        <p className="tc_lead">You will need to update the bank account number and IFSC code to enable us to process a refund to Your account. Refunds cannot be processed to third-party accounts, i.e. the name on Your Vibrant Living account should match with the name of the bank account holder provided for refund via NEFT. A refund initiation confirmation by email or SMS at the email address or mobile number provided to Vibrant Living will be sent to You.</p>
                        <p className="tc_lead">All refunds by cheque will be in form of "at par" cheques or via online transfer; basis sole discretion of Vibrant Living.</p>
                        <p className="tc_lead">
                            <b>Terminated Payment Mode</b>
                        </p>
                        <p className="tc_lead">If the original payment method You used to make the payment (credit or debit card or net banking) is no longer valid, we will issue the refund through a cheque. When we receive a payment failure notice from Your bank, we will send You an email asking You to call us. When You call us, we will collect Your address where You want the cheque to be sent and proceed with the refund. Please refer to our Payment Policy for further details.</p>
                        <p className="tc_lead">You explicitly give Your consent to receiving communications (by SMS, email or other mode of communication) sent to You by Vibrant Living, however, You may withdraw Your consent any time at Your sole discretion.</p>
                        <p className="tc_lead">
                            <br/>
                        </p>
                    </div>
                </div>
            </div>
        </section>
        </div>
        <FooterContent />
       </> 
  );
};
export default PrivacyPolicyContent;
